INSERT INTO PRODUCT VALUES(1,4,'phone','iphone 13 pro');
INSERT INTO PRODUCT VALUES(2,5,'headPhone','Sennheiser');
INSERT INTO PRODUCT VALUES(3,6,'laptop','acer nitro 5');
INSERT INTO PRODUCT VALUES(4,6,'console','ps3');
INSERT INTO PRODUCT VALUES(5,4,'pc','hp');
INSERT INTO PRODUCT VALUES(6,6,'accessories','mouse');

INSERT INTO CUSTOMER VALUES(1,'New','Smith','Ryan');
INSERT INTO CUSTOMER VALUES(2,'Loyal','Heaven ','Browning');
INSERT INTO CUSTOMER VALUES(3,'Impulse','Eugene ','Bauer');
INSERT INTO CUSTOMER VALUES(4,'Angry','Felix ','Davis');
INSERT INTO CUSTOMER VALUES(5,'Loyal','Yamilet ','Knight');
INSERT INTO CUSTOMER VALUES(6,'Loyal','Skylar ','Marsh');

INSERT INTO ORDERS VALUES(1,1);
INSERT INTO ORDERS VALUES(1,2);
INSERT INTO ORDERS VALUES(2,6);
INSERT INTO ORDERS VALUES(3,4);
INSERT INTO ORDERS VALUES(4,1);
INSERT INTO ORDERS VALUES(5,3);
INSERT INTO ORDERS VALUES(5,1);
INSERT INTO ORDERS VALUES(5,6);
INSERT INTO ORDERS VALUES(6,3);
INSERT INTO ORDERS VALUES(6,1);
INSERT INTO ORDERS VALUES(6,6);